// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SiteDeQuadrinhos.Data;

#nullable disable

namespace SiteDeQuadrinhos.Migrations
{
    [DbContext(typeof(SiteDeQuadrinhosDBContex))]
    [Migration("20231021211808_TrocaDeTudodnv3")]
    partial class TrocaDeTudodnv3
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("SiteDeQuadrinhos.Models.AutorModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("DataDeNascimento")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Documento")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioId")
                        .IsUnique();

                    b.ToTable("Autor");
                });

            modelBuilder.Entity("SiteDeQuadrinhos.Models.CapituloModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<Guid>("QuadrinhoId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("QuadrinhoId");

                    b.ToTable("Capitulo");
                });

            modelBuilder.Entity("SiteDeQuadrinhos.Models.FavoritoModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<Guid>("QuadrinhoId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("quadrinhoModelId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("usuarioModelId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("quadrinhoModelId");

                    b.HasIndex("usuarioModelId");

                    b.ToTable("FavoritoModel");
                });

            modelBuilder.Entity("SiteDeQuadrinhos.Models.PaginaModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<Guid>("CapituloId")
                        .HasColumnType("char(36)");

                    b.Property<byte[]>("Pagina")
                        .IsRequired()
                        .HasColumnType("longblob");

                    b.HasKey("Id");

                    b.HasIndex("CapituloId");

                    b.ToTable("Pagina");
                });

            modelBuilder.Entity("SiteDeQuadrinhos.Models.QuadrinhoModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<byte[]>("Capa")
                        .IsRequired()
                        .HasColumnType("longblob");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("TagPrincipal")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioId");

                    b.ToTable("Quadrinhos");
                });

            modelBuilder.Entity("SiteDeQuadrinhos.Models.UsuarioModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Email")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("NomeDeUsuario")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Senha")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("NomeDeUsuario")
                        .IsUnique();

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("SiteDeQuadrinhos.Models.AutorModel", b =>
                {
                    b.HasOne("SiteDeQuadrinhos.Models.UsuarioModel", "usuarioModel")
                        .WithOne("Autor")
                        .HasForeignKey("SiteDeQuadrinhos.Models.AutorModel", "UsuarioId");

                    b.Navigation("usuarioModel");
                });

            modelBuilder.Entity("SiteDeQuadrinhos.Models.CapituloModel", b =>
                {
                    b.HasOne("SiteDeQuadrinhos.Models.QuadrinhoModel", "quadrinhoModel")
                        .WithMany("CapituloModel")
                        .HasForeignKey("QuadrinhoId");

                    b.Navigation("quadrinhoModel");
                });

            modelBuilder.Entity("SiteDeQuadrinhos.Models.FavoritoModel", b =>
                {
                    b.HasOne("SiteDeQuadrinhos.Models.QuadrinhoModel", "quadrinhoModel")
                        .WithMany("favoritosList")
                        .HasForeignKey("quadrinhoModelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SiteDeQuadrinhos.Models.UsuarioModel", "usuarioModel")
                        .WithMany("favoritoList")
                        .HasForeignKey("usuarioModelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("quadrinhoModel");

                    b.Navigation("usuarioModel");
                });

            modelBuilder.Entity("SiteDeQuadrinhos.Models.PaginaModel", b =>
                {
                    b.HasOne("SiteDeQuadrinhos.Models.CapituloModel", "capituloModel")
                        .WithMany("PaginaModel")
                        .HasForeignKey("CapituloId");

                    b.Navigation("capituloModel");
                });

            modelBuilder.Entity("SiteDeQuadrinhos.Models.QuadrinhoModel", b =>
                {
                    b.HasOne("SiteDeQuadrinhos.Models.UsuarioModel", "usuarioModel")
                        .WithMany("Quadrinhos")
                        .HasForeignKey("UsuarioId");

                    b.Navigation("usuarioModel");
                });

            modelBuilder.Entity("SiteDeQuadrinhos.Models.CapituloModel", b =>
                {
                    b.Navigation("PaginaModel");
                });

            modelBuilder.Entity("SiteDeQuadrinhos.Models.QuadrinhoModel", b =>
                {
                    b.Navigation("CapituloModel");

                    b.Navigation("favoritosList");
                });

            modelBuilder.Entity("SiteDeQuadrinhos.Models.UsuarioModel", b =>
                {
                    b.Navigation("Autor");

                    b.Navigation("Quadrinhos");

                    b.Navigation("favoritoList");
                });
#pragma warning restore 612, 618
        }
    }
}
