// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SiteDeQuadrinhos.Data;

#nullable disable

namespace SiteDeQuadrinhos.Migrations
{
    [DbContext(typeof(SiteDeQuadrinhosDBContex))]
    partial class SiteDeQuadrinhosDBContexModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("SiteDeQuadrinhos.Models.AutorModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("DataDeNascimento")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Documento")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("usuarioModelId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("usuarioModelId");

                    b.ToTable("Autor");
                });

            modelBuilder.Entity("SiteDeQuadrinhos.Models.CapituloModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<Guid>("QuadrinhoId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("quadrinhoModelId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("quadrinhoModelId");

                    b.ToTable("Capitulo");
                });

            modelBuilder.Entity("SiteDeQuadrinhos.Models.PaginaModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<Guid>("CapituloId")
                        .HasColumnType("char(36)");

                    b.Property<byte[]>("Pagina")
                        .IsRequired()
                        .HasColumnType("longblob");

                    b.Property<Guid>("capituloModelId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("capituloModelId");

                    b.ToTable("Pagina");
                });

            modelBuilder.Entity("SiteDeQuadrinhos.Models.QuadrinhoModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<byte[]>("Capa")
                        .IsRequired()
                        .HasColumnType("longblob");

                    b.Property<byte[]>("Capitulo")
                        .IsRequired()
                        .HasColumnType("longblob");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("TagPrincipal")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("usuarioModelId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("usuarioModelId");

                    b.ToTable("Quadrinhos");
                });

            modelBuilder.Entity("SiteDeQuadrinhos.Models.UsuarioModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("NomeDeUsuario")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Senha")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.HasKey("Id");

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("SiteDeQuadrinhos.Models.AutorModel", b =>
                {
                    b.HasOne("SiteDeQuadrinhos.Models.UsuarioModel", "usuarioModel")
                        .WithMany()
                        .HasForeignKey("usuarioModelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("usuarioModel");
                });

            modelBuilder.Entity("SiteDeQuadrinhos.Models.CapituloModel", b =>
                {
                    b.HasOne("SiteDeQuadrinhos.Models.QuadrinhoModel", "quadrinhoModel")
                        .WithMany()
                        .HasForeignKey("quadrinhoModelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("quadrinhoModel");
                });

            modelBuilder.Entity("SiteDeQuadrinhos.Models.PaginaModel", b =>
                {
                    b.HasOne("SiteDeQuadrinhos.Models.CapituloModel", "capituloModel")
                        .WithMany()
                        .HasForeignKey("capituloModelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("capituloModel");
                });

            modelBuilder.Entity("SiteDeQuadrinhos.Models.QuadrinhoModel", b =>
                {
                    b.HasOne("SiteDeQuadrinhos.Models.UsuarioModel", "usuarioModel")
                        .WithMany()
                        .HasForeignKey("usuarioModelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("usuarioModel");
                });
#pragma warning restore 612, 618
        }
    }
}
